feature_sets = {
    "Basic": [
        "mean_fix_duration",
        "median_fix_duration",
        "mean_saccade_length",
        "median_saccade_length",
    ],
    "Significant": [
        "age",
        "mean_saccade_length",
        "percent_unseen_fruits",
        "median_saccade_length",
        "num_blinks_per_min",
        "mean_fix_dist_to_object",
        "median_blink_duration",
        "mean_blink_duration",
        "mean_fix_dist_to_fruit",
        "FFD",
        "median_fix_dist_to_object",
        "FIC_std",
    ],
    "Spatial": ["FIC_mean", "FIC_std", "FFD"],
    "Fixation": ["mean_fix_duration", "median_fix_duration", "num_fixations_per_min"],
    "Saccade": ["mean_saccade_length", "median_saccade_length", "num_saccades_per_min"],
    "Latency": ["mean_latency", "median_latency", "std_latency", "max_latency"],
    "Blinks": ["median_blink_duration", "mean_blink_duration", "num_blinks_per_min"],
    "Most Important": [
        "median_blink_duration",
        "mean_blink_duration",
        "percent_unseen_fruits",
        "num_blinks_per_min",
        "mean_saccade_length",
        "FFD",
    ],
    "AOI": [
        "mean_fix_dist_to_object",
        "median_fix_dist_to_object",
        "mean_fix_dist_to_fruit",
        "median_fix_dist_to_fruit",
        "percent_fixations_outside_bbox",
        "percent_unseen_fruits",
    ],
    "All": [
        "mean_fix_duration",
        "median_fix_duration",
        "mean_saccade_length",
        "median_saccade_length",
        "mean_blink_duration",
        "median_blink_duration",
        "num_fixations_per_min",
        "num_blinks_per_min",
        "num_saccades_per_min",
        "age",
        "mean_fix_dist_to_object",
        "median_fix_dist_to_object",
        "mean_fix_dist_to_fruit",
        "median_fix_dist_to_fruit",
        "percent_fixations_outside_bbox",
        "mean_latency",
        "median_latency",
        "std_latency",
        "max_latency",
        "percent_unseen_fruits",
        "FIC_mean",
        "FIC_std",
        "FFD",
    ],
}
