plotting_names = {
    "mean_fix_duration": "Mean Fixation Duration [ms]",
    "median_fix_duration": "Median Fixation Duration [ms]",
    "mean_saccade_length": "Mean Saccade Length [px]",
    "median_saccade_length": "Median Saccade Length [px]",
    "mean_blink_duration": "Mean Blink Duration [ms]",
    "median_blink_duration": "Median Blink Duration [ms]",
    "num_fixations_per_min": "Fixations per Minute",
    "num_blinks_per_min": "Blinks per Minute",
    "num_saccades_per_min": "Saccades per Minute",
    "age": "Age",
    "ran_score": "RAN Score",
    "mean_fix_dist_to_object": "Mean Distance to Object [px]",
    "median_fix_dist_to_object": "Median Distance to Object [px]",
    "mean_fix_dist_to_fruit": "Mean Distance to Fruit [px]",
    "median_fix_dist_to_fruit": "Median Distance to Fruit [px]",
    "percent_fixations_outside_bbox": "% Fixations Outside AOI",
    "mean_latency": "Mean Latency",
    "median_latency": "Median Latency",
    "std_latency": "SD Latency",
    "max_latency": "Max Latency",
    "percent_unseen_fruits": "% Un-Fixated Fruits",
    "FIC_mean": "Mean FIC",
    "FIC_std": "SD FIC",
    "FFD": "FFD",
}
